### ISSUE TITLE
After-action donate ask + progress indicator

### ISSUE THREAD

**Issue by matthew-hinders-anderson** [350org/ak_intl_v3#2]
1. Add a yes/no choice for the share ask
2. Add a third donate ask following the share ask
3. Add a progress indicator that appears after the form submit, indicating the sign/share/donate flow

screenshot: https://d2ddoduugvun08.cloudfront.net/items/1w441z2p342v0o0u0K3h/Image%202019-02-20%20at%2012.33.20%20PM.png

demo: https://act.350.org/sign/join-climate-movement_ptc?variant=1

**Comment by suzigrishpul** [comment]
looks great!
---
suzi grishpul
web developer
pronouns: she/her/they/them
location: Denver, CO, USA (UTC-6)
350.org

**Comment by nadiagorchakova350** [comment]
hey @matthew-hinders-anderson 
asked data team to help figure out the real-life effectiveness of our new flow. in order to do that, they need us to append source parameter to the URL to start tracking the source of donations.

here's the suggestion from Tara:
"
The remedy that I am proposing is for Web to append a source parameter to the URL that leads to the donation form. For now, I propose we use the simple format 'aa_<page_id>'. So in this case, my URL would have been https://act.350.org/donate/af-en/?amount=3&source=aa_281. This will tell us that someone joined on page 281 and then made this donation as an after-action. In our queries, we will be able to link the join action and donation action together. Without the source field, we don't have a way of finding out which donations were made as the result of after-action activity."

could we do that?

**Comment by matthew-hinders-anderson** [comment]
@nadiagorchakova350 just added this!

https://cl.ly/33d35aa94653

**Comment by nadiagorchakova350** [comment]
awesome, thanks! I let Tara and Julia know
